<?php

    session_start();
    
    error_reporting(E_ALL);
    ini_set('display_errors', 1);

    include('db_conection.php');
    include('functions.php');
    
    if(isset($_SESSION['user_data'])){
        $user_data = $_SESSION['user_data'];
        
        if ($user_data) {
            $name = $user_data['name'];
            $id = $user_data['id'];
        }
    }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sustainable Energy</title>
    <link rel="icon" href="media/tesla-icon.png" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="css/energy.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="header">
        <div class="navbar">
        <a href="index.php"><img src="media/logo.png" alt="Logo" class="logo"></a>
            <ul>
                <li><a href="cars.php">Vehicules</a></li>
                <li><a href="#">Energy</a></li>
                <li><a href="charging.php">Charging</a></li>
                <li><a href="about.php">Discover</a></li>
                <li><a href="shop.php">Shop</a></li>
            </ul>
            <?php

                echo '   <ul>';
                if (isset($id)) {
                    echo '       <li>' . $name . '</li>';
                    echo '       <li>';
                    echo '           <form action="logout.php" method="post" class="logout-form">';
                    echo '               <input type="hidden" name="user_id" value="' . $id . '">';
                    echo '               <button style="font-size:24px"> <i class="fas fa-power-off"></i>';
                    echo '           </form>';
                    echo '       </li>';
                } else {
                    echo '       <li><a href="contact.php" alt="support"><i class="far fa-question-circle" style="font-size:24px"></i></a></li>';
                    echo '       <li><a href="#" alt="language"><i class="fas fa-globe" style="font-size:20px"></i></a></li>';
                    echo '       <li><a href="signup.php" alt="teslaaccount"><i class="far fa-user-circle" style="font-size:20px"></i></a></li>';
                }
                echo '   </ul>';
            ?> 
        </div>
        <div class="related" id="related" >
            <h1>Solar Panels for Your Home</h1><br>
            
        </div>
        <div class="p"><p>Lowest Cost Solar Panels in Africa</p></div>
        <div class="info">
            <ul>
                <li>Guaranteed Lowest Price in The World</li>
                <li>Integrated Product Ecosystem</li>
                <li>24/7 System Performance Monitoring</li>
            </ul>
        </div>
        <div class="order">
            <a href="shop.php">Order Now</a>
            <a href="#">Schedule a consultation</a>
        </div>
    </div>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/425_HP_SolarPanels_D.avif" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Electricity For Less</h1>
            <p class="desc">
            The Tesla Solar roof is an innovative roofing solution that seamlessly integrates solar panels into your home's roof. It combines aesthetics with functionality, allowing you to generate clean energy while maintaining the appearance of a traditional roof.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/Homepage-Powerwall-Desktop.avif" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Powerwall</h1>
            <p class="desc">
            The Tesla Powerwall is a home battery system that stores excess energy generated by solar panels or during off-peak hours. It enables you to use stored energy during peak demand or in the event of a power outage, providing greater energy independence and reducing reliance on the grid.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/425_Design_D.avif" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Electricity For Less</h1>
            <p class="desc">
    Use solar energy to power your home and reduce your dependence on the grid. Purchase solar at the lowest price of any national provider with Tesla's price match guarantee and take control of your monthly electricity bill. Schedule a virtual consultation with a Tesla Advisor to learn more.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/solar-panel-closeup.jpg" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>solar-panel</h1>
            <p class="desc">
    Use solar energy to power your home and reduce your dependence on the grid. Purchase solar at the lowest price of any national provider with Tesla's price match guarantee and take control of your monthly electricity bill. Schedule a virtual consultation with a Tesla Advisor to learn more.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/solar.jpg" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Installation Solar Panel</h1>
            <p class="desc">
    Use solar energy to power your home and reduce your dependence on the grid. Purchase solar at the lowest price of any national provider with Tesla's price match guarantee and take control of your monthly electricity bill. Schedule a virtual consultation with a Tesla Advisor to learn more.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/Mega-Menu-Energy-Powerwall-US.avif" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Energy-Powerwall</h1>
            <p class="desc">
    Use solar energy to power your home and reduce your dependence on the grid. Purchase solar at the lowest price of any national provider with Tesla's price match guarantee and take control of your monthly electricity bill. Schedule a virtual consultation with a Tesla Advisor to learn more.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
    <section class="container_shop" id="more">
            <div class="images">
            <img src="media/energy/Mega-Menu-Energy-Megapack.avif" />
            </div>
            <p class="pick">Hot Model</p>
            <div class="product">
            <h3>Savings</h3><br>
            <h1>Energy-Megapack</h1>
            <p class="desc">
    Use solar energy to power your home and reduce your dependence on the grid. Purchase solar at the lowest price of any national provider with Tesla's price match guarantee and take control of your monthly electricity bill. Schedule a virtual consultation with a Tesla Advisor to learn more.</p>
            <div class="buttons">
                <button class="checkout"><a href="product2.php">more details</a></button>
                <button class="fav">Schedule</button>
            </div>
            </div>
    </section>
</body>
</html>